import serial


class iHSV:
    supported_motor_versions = {
        # key: long name for combo-checkbox
        # value: short name used program internally
        'iHSV57 v6x': 'v6'
    }

    rs232_settings = {
        'v6':{
            'baudrate': 57600,
            'bytesize': 8,
            'parity': serial.PARITY_EVEN,
            'stopbits': 1,
            'timeout': 0.5
        }
    }
    motor_parameter = {
        'v6': {
            "P00_Parameter_of_motor_and_driver": {
                "P00-00": {
                    "Code": "P00-00",
                    "Name": "Motor code",
                    "set": "7",
                    "set_range": "0-65535",
                    "Default": "2000",
                    "Unit": "",
                    "Set_method": "downtime setting",
                    "ChangeCondition": "Re power",
                    "Address": "0x0000",
                    "Min": "0",
                    "Max": "65535",
                    "Description": "The factory has been set up , no need to set up again.\n0:P0-01 to P0-17 make sense\n\n2000: absolute value encoder motor, P0-01- to P0-05 automatically identify by driver.",
                    "Symbol": "FALSE",
                    "decimal_place": "0",
                    "authority": "1",
                    "shutdown_set": "True",
                    "Keep": "false"
                },
                "P00-01": {
                    "Code": "P00-01",
                    "Name": "Rated speed of motor",
                    "set": "3000",
                    "set_range": "1-6000",
                    "Default": "0",
                    "Unit": "rpm",
                    "Set_method": "downtime setting",
                    "ChangeCondition": "Re power",
                    "Address": "0x0001",
                    "Min": "1",
                    "Max": "6000",
                    "Description": "Set range: 1-6000, unit: RPM\n\nThe factory has been set up no need set up again",
                    "Symbol": "FALSE",
                    "decimal_place": "0",
                    "authority": "1",
                    "shutdown_set": "True",
                    "Keep": "false"
                },
                "P00-02": {
                    "Code": "P00-02",
                    "Name": "Rated torque of motor",
                    "set": "0",
                    "set_range": "0.01-655.35",
                    "Default": "0",
                    "Unit": "N.M",
                    "Set_method": "downtime setting",
                    "ChangeCondition": "Re power",
                    "Address": "0x0002",
                    "Min": "0.01",
                    "Max": "655.35",
                    "Description": "Setting range: 0.01-655.35, unit: N.M\n\nAccording to the motor settings, the factory setting has done",
                    "Symbol": "FALSE",
                    "decimal_place": "2",
                    "authority": "10",
                    "shutdown_set": "True",
                    "Keep": "false"
                },
                "P00-03": {
                    "Code": "P00-03",
                    "Name": "Rated current of motor",
                    "set": "6",
                    "set_range": "0.01-655.35",
                    "Default": "0",
                    "Unit": "A",
                    "Set_method": "downtime setting",
                    "ChangeCondition": "Re power",
                    "Address": "0x0003",
                    "Min": "0.01",
                    "Max": "655.35",
                    "Description": "Setting range: 0.01-655.35, unit: N.M\n\nAccording to the motor settings, the factory setting has done",
                    "Symbol": "FALSE",
                    "decimal_place": "2",
                    "authority": "1",
                    "shutdown_set": "True",
                    "Keep": "false"
                },
                "P00-04": {
                    "Code": "P00-04",
                    "Name": "Motor moment of inertia",
                    "set": "0,03",
                    "set_range": "0.01-655.35",
                    "Default": "0",
                    "Unit": "kg.cm²",
                    "Set_method": "downtime setting",
                    "ChangeCondition": "Re power",
                    "Address": "0x0004",
                    "Min": "0.01",
                    "Max": "655.35",
                    "Description": "Setting range: 0.01-655.35, unit:kg.cm²\n\nAccording to the motor settings, the factory setting has done",
                    "Symbol": "FALSE",
                    "decimal_place": "2",
                    "authority": "1",
                    "shutdown_set": "True",
                    "Keep": "false"
                },
                "P00-05": {
                    "Code": "P00-05",
                    "Name": "Pole number of motor",
                    "set": "4",
                    "set_range": "1-31",
                    "Default": "0",
                    "Unit": "Opposite pole",
                    "Set_method": "downtime setting",
                    "ChangeCondition": "Re power",
                    "Address": "0x0005",
                    "Min": "1",
                    "Max": "31",
                    "Description": "Set range: 1-31, unit: opposite pole\nAccording to the motor settings, the factory setting has done",
                    "Symbol": "FALSE",
                    "decimal_place": "0",
                    "authority": "1",
                    "shutdown_set": "True",
                    "Keep": "false"
                },
                "P00-10": {
                    "Code": "P00-10",
                    "Name": "Incremental encoder number",
                    "set": "1000",
                    "set_range": "0-65535",
                    "Default": "0",
                    "Unit": "",
                    "Set_method": "downtime setting",
                    "ChangeCondition": "Re power",
                    "Address": "0x000A",
                    "Min": "0",
                    "Max": "65535",
                    "Description": "根据所配电机设置，出厂已设好 According to the matched motor settings, factroy setting has done",
                    "Symbol": "FALSE",
                    "decimal_place": "0",
                    "authority": "1",
                    "shutdown_set": "True",
                    "Keep": "false"
                },
                "P00-11": {
                    "Code": "P00-11",
                    "Name": "Incremental encoder Z pulse electric angle",
                    "set": "300",
                    "set_range": "0-65535",
                    "Default": "0",
                    "Unit": "",
                    "Set_method": "downtime setting",
                    "ChangeCondition": "Re power",
                    "Address": "0x000B",
                    "Min": "0",
                    "Max": "65535",
                    "Description": "根据所配电机设置，出厂已设好 According to the matched motor settings, factroy setting has done",
                    "Symbol": "FALSE",
                    "decimal_place": "0",
                    "authority": "1",
                    "shutdown_set": "True",
                    "Keep": "false"
                },
                "P00-12": {
                    "Code": "P00-12",
                    "Name": "Initial angle of rotor 1",
                    "set": "150",
                    "set_range": "0-360",
                    "Default": "0",
                    "Unit": "1°",
                    "Set_method": "downtime setting",
                    "ChangeCondition": "Re power",
                    "Address": "0x000C",
                    "Min": "0",
                    "Max": "360",
                    "Description": "根据所配电机设置，出厂已设好 According to the matched motor settings, factroy setting has done",
                    "Symbol": "FALSE",
                    "decimal_place": "0",
                    "authority": "1",
                    "shutdown_set": "True",
                    "Keep": "false"
                },
                "P00-13": {
                    "Code": "P00-13",
                    "Name": "Initial angle of rotor 2",
                    "set": "270",
                    "set_range": "0-360",
                    "Default": "0",
                    "Unit": "1°",
                    "Set_method": "downtime setting",
                    "ChangeCondition": "Re power",
                    "Address": "0x000D",
                    "Min": "0",
                    "Max": "360",
                    "Description": "根据所配电机设置，出厂已设好 According to the matched motor settings, factroy setting has done",
                    "Symbol": "FALSE",
                    "decimal_place": "0",
                    "authority": "1",
                    "shutdown_set": "True",
                    "Keep": "false"
                },
                "P00-14": {
                    "Code": "P00-14",
                    "Name": "Initial angle of rotor 3",
                    "set": "210",
                    "set_range": "0-360",
                    "Default": "0",
                    "Unit": "1°",
                    "Set_method": "downtime setting",
                    "ChangeCondition": "Re power",
                    "Address": "0x000E",
                    "Min": "0",
                    "Max": "360",
                    "Description": "根据所配电机设置，出厂已设好 According to the matched motor settings, factroy setting has done",
                    "Symbol": "FALSE",
                    "decimal_place": "0",
                    "authority": "1",
                    "shutdown_set": "True",
                    "Keep": "false"
                },
                "P00-15": {
                    "Code": "P00-15",
                    "Name": "Initial angle of rotor 4",
                    "set": "30",
                    "set_range": "0-360",
                    "Default": "0",
                    "Unit": "1°",
                    "Set_method": "downtime setting",
                    "ChangeCondition": "Re power",
                    "Address": "0x000F",
                    "Min": "0",
                    "Max": "360",
                    "Description": "根据所配电机设置，出厂已设好 According to the matched motor settings, factroy setting has done",
                    "Symbol": "FALSE",
                    "decimal_place": "0",
                    "authority": "1",
                    "shutdown_set": "True",
                    "Keep": "false"
                },
                "P00-16": {
                    "Code": "P00-16",
                    "Name": "Initial angle of rotor 5",
                    "set": "90",
                    "set_range": "0-360",
                    "Default": "0",
                    "Unit": "1°",
                    "Set_method": "downtime setting",
                    "ChangeCondition": "Re power",
                    "Address": "0x0010",
                    "Min": "0",
                    "Max": "360",
                    "Description": "根据所配电机设置，出厂已设好 According to the matched motor settings, factroy setting has done",
                    "Symbol": "FALSE",
                    "decimal_place": "0",
                    "authority": "1",
                    "shutdown_set": "True",
                    "Keep": "false"
                },
                "P00-17": {
                    "Code": "P00-17",
                    "Name": "Initial angle of rotor 6",
                    "set": "330",
                    "set_range": "0-360",
                    "Default": "0",
                    "Unit": "1°",
                    "Set_method": "downtime setting",
                    "ChangeCondition": "Re power",
                    "Address": "0x0011",
                    "Min": "0",
                    "Max": "360",
                    "Description": "根据所配电机设置，出厂已设好 According to the matched motor settings, factroy setting has done",
                    "Symbol": "FALSE",
                    "decimal_place": "0",
                    "authority": "1",
                    "shutdown_set": "True",
                    "Keep": "false"
                },
                "P00-21": {
                    "Code": "P00-21",
                    "Name": "RS232 communication baud rate",
                    "set": "2",
                    "set_range": "0-3",
                    "Default": "0",
                    "Unit": "---",
                    "Set_method": "downtime setting",
                    "ChangeCondition": "Re power",
                    "Address": "0x0015",
                    "Min": "0",
                    "Max": "3",
                    "Description": "Set range: 0-3\n\nBaud rate when selecting communication with PC\n\n0:9600\n\n1:19200\n\n2:57600\n\n3:115200",
                    "Symbol": "FALSE",
                    "decimal_place": "0",
                    "authority": "0",
                    "shutdown_set": "True",
                    "Keep": "false"
                },
                "P00-23": {
                    "Code": "P00-23",
                    "Name": "slave address",
                    "set": "1",
                    "set_range": "0-255",
                    "Default": "1",
                    "Unit": "--",
                    "Set_method": "downtime setting",
                    "ChangeCondition": "Re power",
                    "Address": "0x0017",
                    "Min": "0",
                    "Max": "255",
                    "Description": "Set range: 0-255, default 1\n\nSet up according to equipment requirement",
                    "Symbol": "FALSE",
                    "decimal_place": "0",
                    "authority": "0",
                    "shutdown_set": "True",
                    "Keep": "false"
                },
                "P00-24": {
                    "Code": "P00-24",
                    "Name": "Modbus communication baud rate",
                    "set": "7",
                    "set_range": "0-7",
                    "Default": "2",
                    "Unit": "---",
                    "Set_method": "downtime setting",
                    "ChangeCondition": "Re power",
                    "Address": "0x0018",
                    "Min": "0",
                    "Max": "7",
                    "Description": "Set range：0-7，default 2\n0:2400\n1:4800\n2:9600\n3:19200\n4:38400\n5:57600\n6:115200\n7:25600",
                    "Symbol": "FALSE",
                    "decimal_place": "0",
                    "authority": "0",
                    "shutdown_set": "True",
                    "Keep": "false"
                },
                "P00-25": {
                    "Code": "P00-25",
                    "Name": "Check mode",
                    "set": "1",
                    "set_range": "0-3",
                    "Default": "1",
                    "Unit": "---",
                    "Set_method": "downtime setting",
                    "ChangeCondition": "Re power",
                    "Address": "0x0019",
                    "Min": "0",
                    "Max": "3",
                    "Description": "0: no check, 2 bit stop bit.\n\n1: parity check, 1 bit stop bit.\n\n2: odd check, 1 bit stop bit.\n\n3: no check, 1 bit stop bit.",
                    "Symbol": "FALSE",
                    "decimal_place": "0",
                    "authority": "0",
                    "shutdown_set": "True",
                    "Keep": "false"
                },
                "P00-26": {
                    "Code": "P00-26",
                    "Name": "Modbus Communication response delay",
                    "set": "0",
                    "set_range": "0-100",
                    "Default": "0",
                    "Unit": "1ms",
                    "Set_method": "operate setting",
                    "ChangeCondition": "Re power",
                    "Address": "0x001A",
                    "Min": "0",
                    "Max": "100",
                    "Description": "---",
                    "Symbol": "FALSE",
                    "decimal_place": "0",
                    "authority": "0",
                    "shutdown_set": "True",
                    "Keep": "false"
                },
                "P00-40": {
                    "Code": "P00-40",
                    "Name": "Over temperature protection settings",
                    "set": "0",
                    "set_range": "0-1",
                    "Default": "1",
                    "Unit": "1ohm",
                    "Set_method": "downtime setting",
                    "ChangeCondition": "Re power",
                    "Address": "0x0028",
                    "Min": "0",
                    "Max": "1",
                    "Description": "---",
                    "Symbol": "FALSE",
                    "decimal_place": "0",
                    "authority": "0",
                    "shutdown_set": "True",
                    "Keep": "true"
                }
            },
            "P01_main_control_parameter": {
                "P01-01": {
                    "Code": "P01-01",
                    "Name": "Control mode setting",
                    "Setting": "0",
                    "set_range": "0-6",
                    "Default": "0",
                    "Unit": "---",
                    "Set_Method": "Shutdown setting",
                    "ChangeCondition": "Immediate",
                    "Address": "0x0065",
                    "Min": "0",
                    "Max": "6",
                    "Description": "Set range: 0-6\n\n0: position control mode\n\n1: speed control mode\n\n2: torque control mode\n\n3: speed and torque control mode. You need to use an external input port in CN1 for switching, and set the selected DI port input port function selection to 5 (control mode switching). Controlling the logical state of the port can switch the control mode.\n\nTerminal effective speed mode\n\nTerminal invalid torque mode\n\n\n\n4: position and speed control mode. You need to use an external input port in CN1 for switching, and set the selected DI port input port function selection to 5 (control mode switching). Controlling the logical state of the port can switch the control mode.\n\nTerminal effective position mode\n\nTerminal invalid speed mode\n\n\n\n5: position and torque control mode. You need to use an external input port in CN1 for switching, and set the selected DI port input port function selection to 5 (control mode switching). Controlling the logical state of the port can switch the control mode.\n\nTerminal effective position mode\n\nTerminal invalid torque mode\n\n\n\n6: full closed loop",
                    "Symbol": "FALSE",
                    "decimal_place": "0",
                    "Permission": "0",
                    "shutdown_setting": "True",
                    "Keep": "false"
                },
                "P01-02": {
                    "Code": "P01-02",
                    "Name": "Real time automatic adjustment mode",
                    "Setting": "1",
                    "set_range": "0-3",
                    "Default": "1",
                    "Unit": "---",
                    "Set_Method": "operation setting",
                    "ChangeCondition": "Immediate",
                    "Address": "0x0066",
                    "Min": "0",
                    "Max": "3",
                    "Description": "Set range: 0-2\n\n0: manually adjust rigidity.\n\n1: standard mode automatically adjusts rigidity. In this mode, the parameters P02-00, P02-01, P02-10, P02-11, P02-13, P02-14, P08-20 will be set automatically according to the rigidity level set by P01-03, and manual adjustment of these parameters will not work. The following parameters are set by the user:\n\nP02-03 (speed feed forward gain), P02-04 (speed feed forward smoothing constant).\n\n2: positioning mode automatically adjusts rigidity. In this mode, the parameters P02-00, P02-01, P02-10, P02-11, P02-13, P02-14, P08-20 will be set automatically according to the rigidity level set by P01-03, and manual adjustment of these parameters will not work. The following parameters will be fixed values and cannot be changed.\n\nP02-03 (speed feed forward gain): 30%\n\nP02-04 (speed feed forward smoothing constant): 0.50\n\n3: Automatically adjust the rigidity 2, in this mode, the parameters P02-00, P02-01, P02-10, P02-11, P02-13, will be set automatically according to the rigidity level set by P01-03, P08-20 will be set automatically according to the load inertia set by P01-04, P02-14 set value is 100, manual adjustment of these parameters will not work. The following parameters are set by the user:\n\nP02-03 (speed feed forward gain), P02-04 (speed feed forward smoothing constant).",
                    "Symbol": "FALSE",
                    "decimal_place": "0",
                    "Permission": "0",
                    "shutdown_setting": "false",
                    "Keep": "false"
                },
                "P01-03": {
                    "Code": "P01-03",
                    "Name": "Real time automatic adjustment of rigidity setting",
                    "Setting": "13",
                    "set_range": "0-31",
                    "Default": "13",
                    "Unit": "---",
                    "Set_Method": "operation setting",
                    "ChangeCondition": "Immediate",
                    "Address": "0x0067",
                    "Min": "0",
                    "Max": "31",
                    "Description": "Set range: 0-31\n\nBuilt in 32 gain parameters, when P01-02 is set to 1, or 2 time to play a role. It can be called directly according to the actual situation. The greater the setting value, the stronger the rigidity.",
                    "Symbol": "FALSE",
                    "decimal_place": "0",
                    "Permission": "0",
                    "shutdown_setting": "false",
                    "Keep": "false"
                },
                "P01-04": {
                    "Code": "P01-04",
                    "Name": "Moment of inertia ratio",
                    "Setting": "1",
                    "set_range": "0-100.00",
                    "Default": "3",
                    "Unit": "1 times",
                    "Set_Method": "operation setting",
                    "ChangeCondition": "Immediate",
                    "Address": "0x0068",
                    "Min": "0",
                    "Max": "100.00",
                    "Description": "Set range: 0-100, unit: times.\n\nSetting the load inertia ratio of the corresponding motor, the setting method is as follows:\n\nP01-04= load inertia / motor moment of inertia\n\nThis inertia ratio can be used to write the parameters after the AF-J-L inertia value is recognized.",
                    "Symbol": "FALSE",
                    "decimal_place": "2",
                    "Permission": "0",
                    "shutdown_setting": "false",
                    "Keep": "false"
                },
                "P01-30": {
                    "Code": "P01-30",
                    "Name": "clasp Brake command - servo OFF delay time (clasp brake opening delay)",
                    "Setting": "100",
                    "set_range": "0-255",
                    "Default": "50",
                    "Unit": "1ms",
                    "Set_Method": "operation setting",
                    "ChangeCondition": "Immediate",
                    "Address": "0x0082",
                    "Min": "0",
                    "Max": "255",
                    "Description": "Set range: 0-255, unit: ms\n\nWhen enabled: After executing enabled instructions, after the P01-30 time, the driver will receive the position instructions.\n\nWhen the motor is in a static state, the time from the lock to the non-energized state after the switch-off command is executed.",
                    "Symbol": "FALSE",
                    "decimal_place": "0",
                    "Permission": "0",
                    "shutdown_setting": "false",
                    "Keep": "false"
                },
                "P01-31": {
                    "Code": "P01-31",
                    "Name": "Speed limit value of clasp brake command output",
                    "Setting": "100",
                    "set_range": "0-3000",
                    "Default": "100",
                    "Unit": "1rpm",
                    "Set_Method": "operation setting",
                    "ChangeCondition": "Immediate",
                    "Address": "0x0083",
                    "Min": "0",
                    "Max": "3000",
                    "Description": "Set range: 0-3000, unit: RPM\n\nWhen the motor is in revolving state, the motor speed threshold of the brake output is effective. Under this threshold, the lock output instruction is valid, otherwise the lock output instruction will be valid after waiting for P01-32 time.",
                    "Symbol": "FALSE",
                    "decimal_place": "0",
                    "Permission": "0",
                    "shutdown_setting": "false",
                    "Keep": "false"
                },
                "P01-32": {
                    "Code": "P01-32",
                    "Name": "Servo OFF clasp brake command waiting time",
                    "Setting": "100",
                    "set_range": "0-255",
                    "Default": "50",
                    "Unit": "1ms",
                    "Set_Method": "operation setting",
                    "ChangeCondition": "Immediate",
                    "Address": "0x0084",
                    "Min": "0",
                    "Max": "255",
                    "Description": "Set range: 0-255, unit: ms\n\nThe longest waiting time of the brake output is when the motor is in rotation.",
                    "Symbol": "FALSE",
                    "decimal_place": "0",
                    "Permission": "0",
                    "shutdown_setting": "false",
                    "Keep": "false"
                }
            },
            "P02_Gain_parameter": {
                "P02-00": {
                    "Code": "P02-00",
                    "Name": "Position control gain 1",
                    "set": "48",
                    "set_range": "0-3000.0",
                    "Default": "48.0",
                    "Unit": "1/S",
                    "Setting_method": "operation setting",
                    "ChangeCondition": "Immediate",
                    "Address": "0x00C8",
                    "Min": "0",
                    "Max": "3000.0",
                    "Description": "Setting range: 0-3000.0, unit: 1/S\n\nThe larger the parameter value, the higher the gain ratio, the greater the stiffness, the smaller the position tracking error and the faster the response. However, excessive vibration and overshoot can be caused by excessive parameters.\n\nThis parameter is for steady state response.",
                    "Symbol": "FALSE",
                    "decimal_place": "1",
                    "Permission": "0",
                    "shutdown_setting_": "false",
                    "Keep": "false"
                },
                "P02-01": {
                    "Code": "P02-01",
                    "Name": "Position control gain 2",
                    "set": "57",
                    "set_range": "0-3000.0",
                    "Default": "57.0",
                    "Unit": "1/S",
                    "Setting_method": "operation setting",
                    "ChangeCondition": "Immediate",
                    "Address": "0x00C9",
                    "Min": "0",
                    "Max": "3000.0",
                    "Description": "Setting range: 0-3000.0, unit: 1/S\n\nThe bigger the proportional gain of the position loop regulator, the bigger the parameter value, the higher the gain ratio, the bigger the stiffness, the smaller the position tracking error, and the faster the response. However, excessive vibration and overshoot can be caused by excessive parameters.\n\nThis parameter is for dynamic response.",
                    "Symbol": "FALSE",
                    "decimal_place": "1",
                    "Permission": "0",
                    "shutdown_setting_": "false",
                    "Keep": "false"
                },
                "P02-03": {
                    "Code": "P02-03",
                    "Name": "Speed feed forward gain",
                    "set": "30",
                    "set_range": "0-100.0",
                    "Default": "30",
                    "Unit": "0.01",
                    "Setting_method": "operation setting",
                    "ChangeCondition": "Immediate",
                    "Address": "0x00CB",
                    "Min": "0",
                    "Max": "100.0",
                    "Description": "Set range: 0-100.0, unit 1%\n\nThe feedforward gain of the speed loop, the larger the parameter value, the smaller the position tracking error of the system, and the faster the response. But the feedforward gain is too large, which makes the position loop of the system unstable and prone to overshoot and vibration.\n\n  Set range: 0-100.0, unit 1%\n\nThe feedforward gain of the speed loop, the larger the parameter value, the smaller the position tracking error of the system, and the faster the response. But the feedforward gain is too large, which makes the position loop of the system unstable and prone to overshoot and vibration.\n\n  Report error",
                    "Symbol": "FALSE",
                    "decimal_place": "1",
                    "Permission": "0",
                    "shutdown_setting_": "false",
                    "Keep": "false"
                },
                "P02-04": {
                    "Code": "P02-04",
                    "Name": "Speed feedforward smoothing constant",
                    "set": "0,5",
                    "set_range": "0-64.00",
                    "Default": "0.5",
                    "Unit": "1ms",
                    "Setting_method": "operation setting",
                    "ChangeCondition": "Immediate",
                    "Address": "0x00CC",
                    "Min": "0",
                    "Max": "64.00",
                    "Description": "Setting range: 0-64.00, unit: ms\n\nThis parameter is used to set the speed loop feed forward filter time constant. The larger the value, the larger the filtering effect, but the larger the phase lag.",
                    "Symbol": "FALSE",
                    "decimal_place": "2",
                    "Permission": "0",
                    "shutdown_setting_": "false",
                    "Keep": "false"
                },
                "P02-10": {
                    "Code": "P02-10",
                    "Name": "Speed proportional gain 1",
                    "set": "27",
                    "set_range": "1.0-2000.0",
                    "Default": "27",
                    "Unit": "1Hz",
                    "Setting_method": "operation setting",
                    "ChangeCondition": "Immediate",
                    "Address": "0x00D2",
                    "Min": "1.0",
                    "Max": "2000.0",
                    "Description": "Setting range: 1.0-2000.0, unit: Hz\n\nThe greater the proportional gain of speed, the greater the servo stiffness, the faster the speed response, but too large is easy to produce vibration and noise.\n\nIf the system does not generate shocks, try to increase the parameter.\n\nThis parameter is for static response.",
                    "Symbol": "FALSE",
                    "decimal_place": "1",
                    "Permission": "0",
                    "shutdown_setting_": "false",
                    "Keep": "false"
                },
                "P02-11": {
                    "Code": "P02-11",
                    "Name": "Velocity integral constant 1",
                    "set": "21",
                    "set_range": "0.1-1000.0",
                    "Default": "10",
                    "Unit": "1ms",
                    "Setting_method": "operation setting",
                    "ChangeCondition": "Immediate",
                    "Address": "0x00D3",
                    "Min": "0.1",
                    "Max": "1000.0",
                    "Description": "Setting range: 1.0-1000.0, unit: ms\n\nThe smaller the setting value is, the faster the integrating speed is, the greater the stiffness is, and the smaller the setting value is, the easier vibration and noise will be produced.\n\nWhen the system does not oscillate, try to reduce the value of this parameter.\n\nThis parameter is for steady state response.",
                    "Symbol": "FALSE",
                    "decimal_place": "1",
                    "Permission": "0",
                    "shutdown_setting_": "false",
                    "Keep": "false"
                },
                "P02-12": {
                    "Code": "P02-12",
                    "Name": "Pseudo differential feedforward control coefficient 1",
                    "set": "100",
                    "set_range": "0-100.0",
                    "Default": "100",
                    "Unit": "0.01",
                    "Setting_method": "operation setting",
                    "ChangeCondition": "Immediate",
                    "Address": "0x00D4",
                    "Min": "0",
                    "Max": "100.0",
                    "Description": "Setting range: 0-100.0, unit: 1%\n\nWhen set to 100.0%, the speed loop adopts PI control, and the dynamic response is fast; when set to 0, the speed loop integral effect is obvious, which can filter low-frequency interference, but the dynamic response is slow.\n\nBy adjusting this coefficient, the velocity loop can have better dynamic response and increase the resistance to low frequency interference.",
                    "Symbol": "FALSE",
                    "decimal_place": "1",
                    "Permission": "0",
                    "shutdown_setting_": "false",
                    "Keep": "false"
                },
                "P02-13": {
                    "Code": "P02-13",
                    "Name": "Speed proportional gain 2",
                    "set": "27",
                    "set_range": "1.0-2000.0",
                    "Default": "27",
                    "Unit": "1Hz",
                    "Setting_method": "operation setting",
                    "ChangeCondition": "Immediate",
                    "Address": "0x00D5",
                    "Min": "1.0",
                    "Max": "2000.0",
                    "Description": "Setting range: 1.0-2000.0, unit: Hz\n\nThe greater the proportional gain of speed, the greater the servo stiffness, the faster the speed response, but too large is easy to produce vibration and noise.\n\nWhen the system does not generate shocks, try to increase the parameter.\n\nThis parameter is for dynamic response.",
                    "Symbol": "FALSE",
                    "decimal_place": "1",
                    "Permission": "0",
                    "shutdown_setting_": "false",
                    "Keep": "false"
                },
                "P02-14": {
                    "Code": "P02-14",
                    "Name": "Velocity integral constant 2",
                    "set": "1000",
                    "set_range": "0.1-1000.0",
                    "Default": "1000",
                    "Unit": "1ms",
                    "Setting_method": "operation setting",
                    "ChangeCondition": "Immediate",
                    "Address": "0x00D6",
                    "Min": "0.1",
                    "Max": "1000.0",
                    "Description": "Setting range: 1.0-1000.0, unit: ms\n\nThe smaller the setting value is, the faster the integrating speed is, the greater the stiffness is, and the smaller the setting value is, the easier vibration and noise will be produced.\n\nWhen the system does not oscillate, try to reduce the value of this parameter.\n\nThis parameter is for dynamic response.",
                    "Symbol": "FALSE",
                    "decimal_place": "1",
                    "Permission": "0",
                    "shutdown_setting_": "false",
                    "Keep": "false"
                },
                "P02-15": {
                    "Code": "P02-15",
                    "Name": "Pseudo differential feedforward control coefficient 2",
                    "set": "100",
                    "set_range": "0-100.0",
                    "Default": "100",
                    "Unit": "0.01",
                    "Setting_method": "operation setting",
                    "ChangeCondition": "Immediate",
                    "Address": "0x00D7",
                    "Min": "0",
                    "Max": "100.0",
                    "Description": "Setting range: 0-100.0, unit: 1%\n\nWhen set to 100.0%, the speed loop adopts PI control, and the dynamic response is fast; when set to 0, the integral effect of the speed loop is obvious, which can filter low-frequency interference, but the dynamic response is slow.\n\nBy adjusting this coefficient, the velocity loop can have better dynamic response and increase the resistance to low frequency interference.",
                    "Symbol": "FALSE",
                    "decimal_place": "1",
                    "Permission": "0",
                    "shutdown_setting_": "false",
                    "Keep": "false"
                },
                "P02-19": {
                    "Code": "P02-19",
                    "Name": "Torque feedforward gain",
                    "set": "0",
                    "set_range": "0-30000",
                    "Default": "0",
                    "Unit": "0.01",
                    "Setting_method": "operation setting",
                    "ChangeCondition": "Immediate",
                    "Address": "0x00DB",
                    "Min": "0",
                    "Max": "30000",
                    "Description": "Set range: 0-30000, unit: 1%\n\nSet the feedforward weighting value of the current loop. The parameter is weighted by the derivative of the speed instruction, and the current loop is added.",
                    "Symbol": "FALSE",
                    "decimal_place": "0",
                    "Permission": "0",
                    "shutdown_setting_": "false",
                    "Keep": "false"
                },
                "P02-20": {
                    "Code": "P02-20",
                    "Name": "Torque feedforward smoothing constant",
                    "set": "0,8",
                    "set_range": "0-64.0",
                    "Default": "0.8",
                    "Unit": "1ms",
                    "Setting_method": "operation setting",
                    "ChangeCondition": "Immediate",
                    "Address": "0x00DC",
                    "Min": "0",
                    "Max": "64.0",
                    "Description": "Setting range: 0-64.00, unit: ms\n\nThis parameter is used to set the torque feedforward filter time constant.",
                    "Symbol": "FALSE",
                    "decimal_place": "2",
                    "Permission": "0",
                    "shutdown_setting_": "false",
                    "Keep": "false"
                },
                "P02-30": {
                    "Code": "P02-30",
                    "Name": "Gain switching mode",
                    "set": "0",
                    "set_range": "0-10",
                    "Default": "7",
                    "Unit": "---",
                    "Setting_method": "operation setting",
                    "ChangeCondition": "Immediate",
                    "Address": "0x00E6",
                    "Min": "0",
                    "Max": "10",
                    "Description": "Set range: 0-10\n\nSetting the first and second gain switching conditions\n\n0 fixed as the first gain P02-00, P02-10, P02-11, P02-12\n\n1 fixed second gain P02-01, P02-13, P02-14, P02-15\n\n2 Invalid DI port set to 9 (gain switching input) for DI input switching: First gain is valid: second gain\n\n3 the torque command greater torque command is greater than the threshold (determined by P02-31 and P02-32) when switching to second gain. Less than the threshold, and at the same time exceeding the P02-33 delay setting, switch to the first gain.\n\n4. Switch to the second gain when the change of speed instruction is larger than the threshold (determined by P02-31 and P02-32). Less than the threshold, and at the same time exceeding the P02-33 delay setting, switch to the first gain.\n\n5 speed instruction, large speed instruction is greater than the threshold (determined by P02-31 and P02-32), switching to second gain. Less than the threshold, and at the same time exceeding the P02-33 delay setting, switch to the first gain.\n\n6 position deviation large position deviation greater than the threshold (determined by P02-31 and P02-32) switch to second gain. Less than the threshold, and at the same time exceeding the P02-33 delay setting, switch to the first gain.\n\n7 there is a location instruction that switches to second gain when there is position instruction. When the location instruction ends and the P02-33 delay is set, switch to the first gain.\n\n8 switch to second gain when unfinished positioning is not completed. The location is completed, and at the same time, when the P02-33 delay setting is exceeded, the switch is switched to the first gain.\n\n9 the actual speed is greater than the threshold (determined by P02-31 and P02-32) when switching to second gain. Less than the threshold, and at the same time exceeding the P02-33 delay setting, switch to the first gain.\n\n10 there is a position command + a real speed switch with a position command to second gain. There is no position instruction and the actual speed is less than the threshold (determined by P02-31 and P02-32), and when the P02-33 delay setting is exceeded, the switch to the first gain.",
                    "Symbol": "FALSE",
                    "decimal_place": "0",
                    "Permission": "0",
                    "shutdown_setting_": "false",
                    "Keep": "false"
                },
                "P02-31": {
                    "Code": "P02-31",
                    "Name": "Gain switching level",
                    "set": "800",
                    "set_range": "0-20000",
                    "Default": "800",
                    "Unit": "---",
                    "Setting_method": "operation setting",
                    "ChangeCondition": "Immediate",
                    "Address": "0x00E7",
                    "Min": "0",
                    "Max": "20000",
                    "Description": "Set range: 0-20000\n\nThe threshold of gain switching is determined.\n\nTorque unit: 1000bit=25% rated torque\n\nSpeed unit: 1000bit=200 turns to per minute.\n\nLocation unit: 131072bit per lap.",
                    "Symbol": "FALSE",
                    "decimal_place": "0",
                    "Permission": "0",
                    "shutdown_setting_": "false",
                    "Keep": "false"
                },
                "P02-32": {
                    "Code": "P02-32",
                    "Name": "Gain switching hysteresis",
                    "set": "100",
                    "set_range": "0-20000",
                    "Default": "100",
                    "Unit": "---",
                    "Setting_method": "operation setting",
                    "ChangeCondition": "Immediate",
                    "Address": "0x00E8",
                    "Min": "0",
                    "Max": "20000",
                    "Description": "Set range: 0-20000\n\nHysteresis level for gain switching\n\nTorque unit: 1000bit=25% rated torque\n\nSpeed unit: 1000bit=200 turns to per minute.\n\nLocation unit: 131072bit per lap.",
                    "Symbol": "FALSE",
                    "decimal_place": "0",
                    "Permission": "0",
                    "shutdown_setting_": "false",
                    "Keep": "false"
                },
                "P02-33": {
                    "Code": "P02-33",
                    "Name": "Communication response delay",
                    "set": "10",
                    "set_range": "0-1000.0",
                    "Default": "10",
                    "Unit": "1ms",
                    "Setting_method": "operation setting",
                    "ChangeCondition": "Immediate",
                    "Address": "0x00E9",
                    "Min": "0",
                    "Max": "1000.0",
                    "Description": "Setting range: 0-1000.0, unit: ms\n\nFrom the second gain to the first gain, the trigger condition is satisfied to the actual switching time.",
                    "Symbol": "FALSE",
                    "decimal_place": "1",
                    "Permission": "0",
                    "shutdown_setting_": "false",
                    "Keep": "false"
                },
                "P02-34": {
                    "Code": "P02-34",
                    "Name": "Position gain switching time",
                    "set": "10",
                    "set_range": "0-1000.0",
                    "Default": "10",
                    "Unit": "1ms",
                    "Setting_method": "operation setting",
                    "ChangeCondition": "Immediate",
                    "Address": "0x00EA",
                    "Min": "0",
                    "Max": "1000.0",
                    "Description": "Setting range: 0-1000.0, unit: ms\n\nPosition control gain 1 smooth switching to position control gain 2 time.",
                    "Symbol": "FALSE",
                    "decimal_place": "1",
                    "Permission": "0",
                    "shutdown_setting_": "false",
                    "Keep": "false"
                },
                "P02-41": {
                    "Code": "P02-41",
                    "Name": "Mode switch level",
                    "set": "10000",
                    "set_range": "0-20000",
                    "Default": "10000",
                    "Unit": "---",
                    "Setting_method": "operation setting",
                    "ChangeCondition": "Immediate",
                    "Address": "0x00F1",
                    "Min": "0",
                    "Max": "20000",
                    "Description": "Set range: 0-20000\n\nSet the threshold of switching.\n\nTorque unit: 1000bit=25% rated torque\n\nSpeed unit: 1000bit=200 turns to per minute.\n\nLocation unit: 131072bit per lap.",
                    "Symbol": "FALSE",
                    "decimal_place": "0",
                    "Permission": "0",
                    "shutdown_setting_": "false",
                    "Keep": "false"
                },
                "P02-50": {
                    "Code": "P02-50",
                    "Name": "Torque command added value",
                    "set": "0",
                    "set_range": "-100.0-100.0",
                    "Default": "0",
                    "Unit": "0.01",
                    "Setting_method": "operation setting",
                    "ChangeCondition": "Immediate",
                    "Address": "0x00FA",
                    "Min": "-100.0",
                    "Max": "100.0",
                    "Description": "Setting range: -100.0-100, unit: 1%\n\nThe position control mode is effective. This value is added to the torque setting value for vertical shaft static torque compensation.",
                    "Symbol": "FALSE",
                    "decimal_place": "1",
                    "Permission": "0",
                    "shutdown_setting_": "false",
                    "Keep": "false"
                },
                "P02-51": {
                    "Code": "P02-51",
                    "Name": "Forward torque compensation",
                    "set": "0",
                    "set_range": "-100.0-100.0",
                    "Default": "0",
                    "Unit": "0.01",
                    "Setting_method": "operation setting",
                    "ChangeCondition": "Immediate",
                    "Address": "0x00FB",
                    "Min": "-100.0",
                    "Max": "100.0",
                    "Description": "Setting range: -100.0-100.0, unit: 1%\n\nThe position control mode is effective. Compensation for forward static friction",
                    "Symbol": "FALSE",
                    "decimal_place": "1",
                    "Permission": "0",
                    "shutdown_setting_": "false",
                    "Keep": "false"
                },
                "P02-52": {
                    "Code": "P02-52",
                    "Name": "Reverse torque compensation",
                    "set": "0",
                    "set_range": "-100.0-100.0",
                    "Default": "0",
                    "Unit": "0.01",
                    "Setting_method": "operation setting",
                    "ChangeCondition": "Immediate",
                    "Address": "0x00FC",
                    "Min": "-100.0",
                    "Max": "100.0",
                    "Description": "Setting range: -100.0-100.0, unit: 1%\n\nThe position control mode is effective. Compensation for reverse static friction",
                    "Symbol": "FALSE",
                    "decimal_place": "2",
                    "Permission": "0",
                    "shutdown_setting_": "false",
                    "Keep": "false"
                },
            },
            "P03_Position_parameters": {
                "P03-00": {
                    "Code": "P03-00",
                    "Name": "Position command source",
                    "set": "0",
                    "set_range": "0-1",
                    "Default": "0",
                    "Unit": "---",
                    "Setting_mode": "stop setting",
                    "ChangeCondition": "Immediate",
                    "Address": "0x012C",
                    "Min": "0",
                    "Max": "1",
                    "Description": "0：Pulse command\n1：Digital given when communication control",
                    "Symbol": "FALSE",
                    "decimal_place": "0",
                    "Right": "0",
                    "Downtime_setting_": "True",
                    "Keep": "false"
                },
                "P03-03": {
                    "Code": "P03-03",
                    "Name": "Instruction pulse inversion",
                    "set": "0",
                    "set_range": "0-1",
                    "Default": "0",
                    "Unit": "---",
                    "Setting_mode": "stop setting",
                    "ChangeCondition": "Immediate",
                    "Address": "0x012F",
                    "Min": "0",
                    "Max": "1",
                    "Description": "To adjust the counting direction of the pulse instruction\n0：Normal.\n1：Reverse direction",
                    "Symbol": "FALSE",
                    "decimal_place": "0",
                    "Right": "0",
                    "Downtime_setting_": "True",
                    "Keep": "false"
                },
                "P03-04": {
                    "Code": "P03-04",
                    "Name": "Position pulse  filtration",
                    "set": "2",
                    "set_range": "0-3",
                    "Default": "0",
                    "Unit": "---",
                    "Setting_mode": "operation setting",
                    "ChangeCondition": "Immediate",
                    "Address": "0x0130",
                    "Min": "0",
                    "Max": "3",
                    "Description": "Setting range：0-3，Unit：us\n0：0.1us。\n1：0.4us\n2：0.8us。\n3：1.6us",
                    "Symbol": "FALSE",
                    "decimal_place": "0",
                    "Right": "0",
                    "Downtime_setting_": "false",
                    "Keep": "false"
                },
                "P03-05": {
                    "Code": "P03-05",
                    "Name": "Location completion judgement condition",
                    "set": "1",
                    "set_range": "0-2",
                    "Default": "1",
                    "Unit": "---",
                    "Setting_mode": "operation setting",
                    "ChangeCondition": "Immediate",
                    "Address": "0x0131",
                    "Min": "0",
                    "Max": "2",
                    "Description": "0：output when the position deviation is less than the P03-06 set value\n1：When the position is completed and the position deviation is less than P03-06, the output is set.\n2：When the position is completed (filtered) and the position deviation is less than P03-06, the outp...",
                    "Symbol": "FALSE",
                    "decimal_place": "0",
                    "Right": "0",
                    "Downtime_setting_": "false",
                    "Keep": "false"
                },
                "P03-06": {
                    "Code": "P03-06",
                    "Name": "Positioning complete(In-Position)\nrange",
                    "set": "30",
                    "set_range": "0-65535",
                    "Default": "100",
                    "Unit": "Encoder unit",
                    "Setting_mode": "operation setting",
                    "ChangeCondition": "Immediate",
                    "Address": "0x0132",
                    "Min": "0",
                    "Max": "65535",
                    "Description": "Set range： 0-65535，Unit：Encoder unit\nThe threshold value used to set the location to complete the output 。When absolute motor is used, the encoder is calculated at 131072bit per loop. Using incremental encoder motor, the loop of encoders  is calculated by encoder line *4.",
                    "Symbol": "FALSE",
                    "decimal_place": "0",
                    "Right": "0",
                    "Downtime_setting_": "false",
                    "Keep": "false"
                },
                "P03-09": {
                    "Code": "P03-09",
                    "Name": "The number of instruction pulses in the rotation of a motor",
                    "set": "4000",
                    "set_range": "0-65535",
                    "Default": "10000",
                    "Unit": "Pulse",
                    "Setting_mode": "operation setting",
                    "ChangeCondition": "Power-on again",
                    "Address": "0x0135",
                    "Min": "0",
                    "Max": "65535",
                    "Description": "Set range ： 0-65535    The absolute encoder motor is used to set the number of instructions pulse when a motor spin a circle .When it is set 0, the parameters of P03-10,P03-11 are valid",
                    "Symbol": "FALSE",
                    "decimal_place": "0",
                    "Right": "0",
                    "Downtime_setting_": "false",
                    "Keep": "false"
                },
                "P03-10": {
                    "Code": "P03-10",
                    "Name": "numerator of electronic gear1",
                    "set": "5",
                    "set_range": "1-65535",
                    "Default": "1",
                    "Unit": "---",
                    "Setting_mode": "operation setting",
                    "ChangeCondition": "Power-on again",
                    "Address": "0x0136",
                    "Min": "1",
                    "Max": "65535",
                    "Description": "When using the absoluted encoder, see 6.1.3Example of electronic gear ratio calculation \nAn incremental calculation formula for electrical gear ratio：\nG = numerator/denominator;\n = C*4/P\nC:Line of encoder ；P: Pulse No.Input per rotation number \nEg：Encoder line is 2500； input pulse No.of per rotation 3200；what is the electrical gear ratio?：\nG= C*4/P = 2500 * 4/ 3200 = 10000/3200 = 25:8\n \n Re：Numerator of 20B encoder is 131072\n   Numerator of 17Z encoder is160000",
                    "Symbol": "FALSE",
                    "decimal_place": "0",
                    "Right": "0",
                    "Downtime_setting_": "false",
                    "Keep": "false"
                },
                "P03-11": {
                    "Code": "P03-11",
                    "Name": "Denominator of electronic gear 1",
                    "set": "4",
                    "set_range": "1-65535",
                    "Default": "1",
                    "Unit": "---",
                    "Setting_mode": "operation setting",
                    "ChangeCondition": "Power-on again",
                    "Address": "0x0137",
                    "Min": "1",
                    "Max": "65535",
                    "Description": "When using the absoluted encoder, see 6.1.3Example of electronic gear ratio calculation \nAn incremental calculation formula for electrical gear ratio：\nG = numerator/denominator;\n = C*4/P\nC:Line of encoder ；P:输入每转脉冲数 Pulse No.Input per rotation number \nEg：Encoder line is 2500； input pulse No.of per rotation 3200；what is the electrical gear ratio?：\nG= C*4/P = 2500 * 4/ 3200 = 10000/3200 = 25:8\n \n Re：Numerator of 20B encoder is 131072\n   Numerator of 17Z encoder is160000",
                    "Symbol": "FALSE",
                    "decimal_place": "0",
                    "Right": "0",
                    "Downtime_setting_": "false",
                    "Keep": "false"
                },
                "P03-15": {
                    "Code": "P03-15",
                    "Name": "position deviation Setting is too large",
                    "set": "2000",
                    "set_range": "0-65535",
                    "Default": "30000",
                    "Unit": "Command unit*10",
                    "Setting_mode": "operation setting",
                    "ChangeCondition": "Immediate",
                    "Address": "0x013B",
                    "Min": "0",
                    "Max": "65535",
                    "Description": "Setting range： 0-65535，Unit：Command unit*10\nSet the number of pulses allowed for deviation, and it will alarm if it exceeds the set value. \nEg：setting value is 20，When the followed deviation is more than 20*10.The driver will be alarmed AL.501（Position devitation is too large）",
                    "Symbol": "FALSE",
                    "decimal_place": "0",
                    "Right": "0",
                    "Downtime_setting_": "false",
                    "Keep": "false"
                },
                "P03-16": {
                    "Code": "P03-16",
                    "Name": "Time constant of Position command smoothing filter",
                    "set": "0",
                    "set_range": "0-1000.0",
                    "Default": "0",
                    "Unit": "1ms",
                    "Setting_mode": "operation setting",
                    "ChangeCondition": "Immediate",
                    "Address": "0x013C",
                    "Min": "0",
                    "Max": "1000.0",
                    "Description": "Setting range： 1000，Unit：ms\nSetting the time constant of a position instruction smooth filter",
                    "Symbol": "FALSE",
                    "decimal_place": "1",
                    "Right": "0",
                    "Downtime_setting_": "false",
                    "Keep": "false"
                }
            },
            "P04_Speed_parameters": {
                "P04-00": {
                    "Code": "P04-00",
                    "Name": "Source of rotational\nspeed",
                    "setting": "1",
                    "Setting_range": "0-3",
                    "Default": "0",
                    "Unit": "---",
                    "Setting_way": "Shutdown setting",
                    "ChangeCondition": "Immediate",
                    "Address": "0x0190",
                    "Min": "0",
                    "Max": "3",
                    "Description": "0：External analog instruction\n1：Digital command (parameters)\n2：Digital instruction\n(communication)\n3：Internal multiple sets of\ninstructions",
                    "Symbol": "FALSE",
                    "Demical_Place": "0",
                    "Permission": "0",
                    "Shutdown_setting": "True",
                    "Keep": "false"
                },
                "P04-01": {
                    "Code": "P04-01",
                    "Name": "Speed analog command inverting",
                    "setting": "0",
                    "Setting_range": "0-1",
                    "Default": "0",
                    "Unit": "---",
                    "Setting_way": "Shutdown setting",
                    "ChangeCondition": "Immediate",
                    "Address": "0x0191",
                    "Min": "0",
                    "Max": "1",
                    "Description": "adjusting the polarity relations of  analog quantities\n0：Normal\n1：Polarity reversal",
                    "Symbol": "FALSE",
                    "Demical_Place": "0",
                    "Permission": "0",
                    "Shutdown_setting": "True",
                    "Keep": "false"
                },
                "P04-02": {
                    "Code": "P04-02",
                    "Name": "Digital speed command value",
                    "setting": "0",
                    "Setting_range": "-6000-6000",
                    "Default": "0",
                    "Unit": "1rpm",
                    "Setting_way": "operation setting",
                    "ChangeCondition": "Immediate",
                    "Address": "0x0192",
                    "Min": "-6000",
                    "Max": "6000",
                    "Description": "Setting range：-6000－6000，Unit：rpm\nWhen P04-00 is set to 1, P04-02 is the setting value of speed control.",
                    "Symbol": "FALSE",
                    "Demical_Place": "0",
                    "Permission": "0",
                    "Shutdown_setting": "false",
                    "Keep": "false"
                },
                "P04-05": {
                    "Code": "P04-05",
                    "Name": "Over-speed alarm value",
                    "setting": "6400",
                    "Setting_range": "0-6500",
                    "Default": "6400",
                    "Unit": "1rpm",
                    "Setting_way": "operation setting",
                    "ChangeCondition": "Immediate",
                    "Address": "0x0195",
                    "Min": "0",
                    "Max": "6500",
                    "Description": "Setting range ：0-6500，Unit：rpm\n Set the maximum allowed speed , exceeding the set value  AL.420 overspeed alarm.",
                    "Symbol": "FALSE",
                    "Demical_Place": "0",
                    "Permission": "0",
                    "Shutdown_setting": "false",
                    "Keep": "false"
                },
                "P04-06": {
                    "Code": "P04-06",
                    "Name": "Positive speed limit value",
                    "setting": "5000",
                    "Setting_range": "0-6000",
                    "Default": "5000",
                    "Unit": "1rpm",
                    "Setting_way": "operation setting",
                    "ChangeCondition": "Immediate",
                    "Address": "0x0196",
                    "Min": "0",
                    "Max": "6000",
                    "Description": "Setting range：0-6000，Unit：rpm\n\nLimit the positive speed of the motor.",
                    "Symbol": "FALSE",
                    "Demical_Place": "0",
                    "Permission": "0",
                    "Shutdown_setting": "false",
                    "Keep": "false"
                },
                "P04-07": {
                    "Code": "P04-07",
                    "Name": "Negative speed limit value",
                    "setting": "-5000",
                    "Setting_range": "-6000-0",
                    "Default": "-5000",
                    "Unit": "1rpm",
                    "Setting_way": "operation setting",
                    "ChangeCondition": "Immediate",
                    "Address": "0x0197",
                    "Min": "-6000",
                    "Max": "0",
                    "Description": "setting range：0- -6000，Unit：rpm\n\nLimiting motor reverse speed",
                    "Symbol": "True",
                    "Demical_Place": "0",
                    "Permission": "0",
                    "Shutdown_setting": "false",
                    "Keep": "false"
                },
                "P04-10": {
                    "Code": "P04-10",
                    "Name": "Zero-speed",
                    "setting": "2",
                    "Setting_range": "0-200",
                    "Default": "2",
                    "Unit": "1rpm",
                    "Setting_way": "operation setting",
                    "ChangeCondition": "Immediate",
                    "Address": "0x019A",
                    "Min": "0",
                    "Max": "200",
                    "Description": "Set range：0-200.0，Unit：rpm\nSetting the zero speed detection threshold value, if motor speed below the threshold can output  \"motor zero speed output\" signal\n  through the output port",
                    "Symbol": "FALSE",
                    "Demical_Place": "0",
                    "Permission": "0",
                    "Shutdown_setting": "false",
                    "Keep": "true"
                },
                "P04-14": {
                    "Code": "P04-14",
                    "Name": "Acceleration time setup",
                    "setting": "500",
                    "Setting_range": "0-10000",
                    "Default": "0",
                    "Unit": "1ms/1000rpm",
                    "Setting_way": "operation setting",
                    "ChangeCondition": "Immediate",
                    "Address": "0x019E",
                    "Min": "0",
                    "Max": "10000",
                    "Description": "Set range：0-10000，Unit：1ms/1000rpm\n\nSetting the acceleration of speed control",
                    "Symbol": "FALSE",
                    "Demical_Place": "0",
                    "Permission": "0",
                    "Shutdown_setting": "false",
                    "Keep": "false"
                },
                "P04-15": {
                    "Code": "P04-15",
                    "Name": "Deceleration time setup",
                    "setting": "500",
                    "Setting_range": "0-10000",
                    "Default": "0",
                    "Unit": "",
                    "Setting_way": "operation setting",
                    "ChangeCondition": "Immediate",
                    "Address": "0x019F",
                    "Min": "0",
                    "Max": "10000",
                    "Description": "Set range：0-10000，Unit：1ms/1000rpm\nSetting deceleration  in controlling speed",
                    "Symbol": "FALSE",
                    "Demical_Place": "0",
                    "Permission": "0",
                    "Shutdown_setting": "false",
                    "Keep": "false"
                }
            },
            "P05_Torque_parameters": {
                "P05-05": {
                    "Code": "P05-05",
                    "Name": "Torque limiting setting source",
                    "setting": "0",
                    "set_range": "0-1",
                    "Default": "0",
                    "Unit": "---",
                    "setting_way": "Shutdown setting",
                    "ChangeCondition": "Immediate",
                    "Address": "0x01F9",
                    "Min": "0",
                    "Max": "1",
                    "Description": "Source for adjusting torque limiting amplitude\n\n0: internal digital quantity (set by P05-10, P05-11 or P05-12, P05-13)\n\n1: external analog (T-REF input from external analog input). In this mode, the amplitude of the positive and negative directions is the same.",
                    "Symbol": "FALSE",
                    "Demical_Place": "0",
                    "Permission": "0",
                    "Shutdown_setting": "True",
                    "Keep": "true"
                },
                "P05-10": {
                    "Code": "P05-10",
                    "Name": "Internal forward torque limiting amplitude",
                    "setting": "200",
                    "set_range": "0-300.0",
                    "Default": "200.0",
                    "Unit": "",
                    "setting_way": "operation setting",
                    "ChangeCondition": "immediate",
                    "Address": "0x01FE",
                    "Min": "0",
                    "Max": "300.0",
                    "Description": "Setting range: 0-300.0, unit: 1%\n\nLimit the positive output of motor, 100 indicates 1 times torque, 300 indicates 3 times torque.\n\nWhen the torque output reaches the limit value, the output signal can be detected through the output torque limit of the DO port.",
                    "Symbol": "FALSE",
                    "Demical_Place": "1",
                    "Permission": "0",
                    "Shutdown_setting": "false",
                    "Keep": "false"
                },
                "P05-11": {
                    "Code": "P05-11",
                    "Name": "Internal reverse torque limiting amplitude",
                    "setting": "-200",
                    "set_range": "-300.0-0",
                    "Default": "-200.0",
                    "Unit": "",
                    "setting_way": "operation setting",
                    "ChangeCondition": "Immediate",
                    "Address": "0x01FF",
                    "Min": "-300.0",
                    "Max": "0",
                    "Description": "Setting range: 0-300.0, unit: 1%\n\nLimit motor reverse output, 100 represents 1 times torque, 300 indicates 3 times torque.\n\nWhen the torque output reaches the limit value, the output signal can be detected through the output torque limit of the DO port.",
                    "Symbol": "True",
                    "Demical_Place": "1",
                    "Permission": "0",
                    "Shutdown_setting": "false",
                    "Keep": "false"
                }
            },
            "P06_IO_parameters": {
                "P06-00": {
                    "Code": "P06-00",
                    "Name": "DI1 input port effective electrical level",
                    "Set": "1",
                    "set_range": "0-4",
                    "Default": "0",
                    "Unit": "---",
                    "Setting_way": "operation setting",
                    "ChangeCondition": "REpower",
                    "Address": "0x0258",
                    "Min": "0",
                    "Max": "4",
                    "Description": "Set range: 0-4, factory settings: 0\n\nSet the valid input of the DI1 input port of CN1.\n\n0: low level active (optical coupler).\n\n1: stands for high level efficiency (optocoupler cut-off).\n\n2: rising edge effective\n\n3: falling edge effective\n\n4: rising and falling edge are all effective.",
                    "Symbol": "FALSE",
                    "Demical_Place": "0",
                    "Permission": "0",
                    "Shutdown_setting": "false",
                    "Keep": "false"
                },
                "P06-20": {
                    "Code": "P06-20",
                    "Name": "DO1 output port effective level",
                    "Set": "1",
                    "set_range": "0-1",
                    "Default": "1",
                    "Unit": "---",
                    "Setting_way": "operation setting",
                    "ChangeCondition": "REpower",
                    "Address": "0x026C",
                    "Min": "0",
                    "Max": "1",
                    "Description": "Set range: 0-1, factory settings: 1\n\n0: when the state is valid, optocoupler cut-off.\n\n1: when the state is valid, the optical coupler turns on.",
                    "Symbol": "FALSE",
                    "Demical_Place": "0",
                    "Permission": "0",
                    "Shutdown_setting": "false",
                    "Keep": "false"
                },
                "P06-22": {
                    "Code": "P06-22",
                    "Name": "DO2 output port effective level",
                    "Set": "1",
                    "set_range": "0-1",
                    "Default": "1",
                    "Unit": "---",
                    "Setting_way": "operation setting",
                    "ChangeCondition": "REpower",
                    "Address": "0x026E",
                    "Min": "0",
                    "Max": "1",
                    "Description": "Set range: 0-1, factory settings: 1\n\n0: when the state is valid, optocoupler cut-off.\n\n1: when the state is valid, the optical coupler turns on.",
                    "Symbol": "FALSE",
                    "Demical_Place": "0",
                    "Permission": "0",
                    "Shutdown_setting": "false",
                    "Keep": "false"
                },
                "P06-23": {
                    "Code": "P06-23",
                    "Name": "Function selection of DO2 output port  (brand-type brake open)",
                    "Set": "2",
                    "set_range": "0-2",
                    "Default": "2",
                    "Unit": "---",
                    "Setting_way": "operation setting",
                    "ChangeCondition": "REpower",
                    "Address": "0x026F",
                    "Min": "0",
                    "Max": "2",
                    "Description": "Set range: 0-11, factory settings: 3\n\n0: pins invalid\n\n1: alarm output\n\n2: brake opening output\n\n3: servo ready output\n\n4: positioning and output.\n\n5: positioning close to output\n\n6: speed consistent output\n\n7: Motor zero speed output\n\n8: torque limit detection output\n\n9: speed limit detection output\n\n10: warning output\n\n11: instruction pulse input rate switching output.\n\n12: origin regression completes output.\n\n13: Electrical origin regression completes output.",
                    "Symbol": "FALSE",
                    "Demical_Place": "0",
                    "Permission": "0",
                    "Shutdown_setting": "false",
                    "Keep": "true"
                }
            },
            "P08_advanced_function_parameter": {
                "P08-19": {
                    "Code": "P08-19",
                    "Name": "Feedback speed lowpass filter constant",
                    "setting": "0,8",
                    "Setting_range": "0-25.00",
                    "Default": "0.8",
                    "Unit": "1ms",
                    "Setting_way": "operation setting",
                    "ChangeCondition": "Immediate",
                    "Address": "0x0333",
                    "Min": "0",
                    "Max": "25.00",
                    "Description": "---",
                    "Symbol": "FALSE",
                    "Demical_Place": "2",
                    "Permission": "0",
                    "Shutdown_setting": "FALSE",
                    "Keep": "false"
                },
                "P08-20": {
                    "Code": "P08-20",
                    "Name": "Torque command filtering constant",
                    "setting": "0,84",
                    "Setting_range": "0-25.00",
                    "Default": "0.8",
                    "Unit": "1ms",
                    "Setting_way": "operation setting",
                    "ChangeCondition": "Immediate",
                    "Address": "0x0334",
                    "Min": "0",
                    "Max": "25.00",
                    "Description": "Setting range: 0-25.00, unit: ms\n\nTorque command filter time constant. When the motor starts screaming, it can be set up appropriately.",
                    "Symbol": "FALSE",
                    "Demical_Place": "2",
                    "Permission": "0",
                    "Shutdown_setting": "FALSE",
                    "Keep": "false"
                },
                "P08-25": {
                    "Code": "P08-25",
                    "Name": "Disturbance torque compensation gain",
                    "setting": "0",
                    "Setting_range": "0-100.0",
                    "Default": "0",
                    "Unit": "％",
                    "Setting_way": "operation setting",
                    "ChangeCondition": "Immediate",
                    "Address": "0x0339",
                    "Min": "0",
                    "Max": "100.0",
                    "Description": "Setting range: 0-100.0\n\nThe disturbance torque observation is worth the gain coefficient. The greater the value, the stronger the ability to resist disturbance torque, but the action noise may also increase.",
                    "Symbol": "FALSE",
                    "Demical_Place": "1",
                    "Permission": "0",
                    "Shutdown_setting": "FALSE",
                    "Keep": "false"
                },
                "P08-26": {
                    "Code": "P08-26",
                    "Name": "Disturbance torque filtering time constant",
                    "setting": "0,8",
                    "Setting_range": "0-25.0",
                    "Default": "0.8",
                    "Unit": "1ms",
                    "Setting_way": "operation setting",
                    "ChangeCondition": "Immediate",
                    "Address": "0x033A",
                    "Min": "0",
                    "Max": "25.0",
                    "Description": "Setting range: 0-25.00, unit: ms\n\nThe larger the numerical value, the stronger the filtering effect and suppressing the action noise. However, excessive phase leads to phase delay, which affects the effect of disturbance torque suppression.",
                    "Symbol": "FALSE",
                    "Demical_Place": "2",
                    "Permission": "0",
                    "Shutdown_setting": "FALSE",
                    "Keep": "false"
                },
            },
        }
    }
    selected_motor_parameter = {
        # definition of parameter which will be read out (and displayed in the table)
        # possible parameters are the keys of <motor_parameter>
        # order of the tuple is used as order for the table
        'v5': (
            'Address',
            'Value',
            'Description'
        ),
        'v6': (
            'Address',
            'Code',
            'Name',
            'Value',
            'Unit',
            'Min',
            'Default',
            'Max',
            'ChangeCondition',
            'Description'
        )
    }
    motor_live_data = {
        'v5': [
            [[0x85, 0x86], False, 'Pos Cmd'],
            [[0x87, 0x88], False, 'Real Pos'],
            [[0x89], True, 'Pos Error'],

            [[0x90], True, 'Vel Cmd [Rpm]'],
            [[0x91], True, 'Real Vel [Rpm]'],
            [[0x92], True, 'Vel Error [Rpm]'],

            [[0xA0], True, 'Torque Current Cmd'],
            [[0xA1], True, 'Real Torque Current'],
        ],
        'v6': [
            [[0x0834, 0x0835], False, 'Pos Cmd'],
            [[0x0836, 0x0837], False, 'Pos Feedback'],
            [[0x0838, 0x0839], True, 'Pos Error'],
            # [[0x083A, 0x083B], True, 'Pos Cmd'],
            # [[0x083C, 0x083D], True, 'Pos Feedback'],
            # [[0x083E], True, 'Pos Error'],

            [[0x0841], True, 'Vel Cmd [rpm]'],
            [[0x0842], True, 'Vel Feedback [rpm]'],

            [[0x0843], True, 'Torque Cmd [%]'],
            [[0x0844], True, 'Torque Feedback [%]']
        ]
    }
    gain_relevant_only_registers = [
        "P02-00",  # Position control gain 1
        "P02-01",  # Position control gain 2
        "P02-03",  # Speed feed forward gain
        "P02-04",  # Speed feedforward smoothing constant
        "P02-10",  # Speed proportional gain 1
        "P02-11",  # Velocity integral constant 1
        "P02-12",  # Pseudo differential feedforward control coefficient 1
        "P02-13",  # Speed proportional gain 2
        "P02-14",  # Velocity integral constant 2
        "P02-15",  # Pseudo differential feedforward control coefficient 2
        "P02-19",  # Torque feedforward gain
        "P02-20",  # Torque feedforward smoothing constant
        "P02-30",  # Gain switching mode
        "P02-31",  # Gain switching level
        "P02-32",  # Gain switching hysteresis
        "P02-33",  # Communication response delay
        "P02-34",  # Position gain switching time
        "P02-41",  # Mode switch level
        "P02-50",  # Torque command added value
        "P02-51",  # Forward torque compensation
        "P02-52",  # Reverse torque compensation
        "P08-19",  # Feedback speed lowpass filter constant
        "P08-20",  # Torque command filtering constant
        "P08-25",  # Disturbance torque compensation gain
        "P08-26",  # Disturbance torque filtering time constant
    ]


    def __init__(self, motor_version):
        if motor_version in self.supported_motor_versions.values():
            self.mv = motor_version
        else:
            raise ValueError('Motor Version not supported')

        self.rs232 = self.rs232_settings[self.mv]
        self.parameter = self.motor_parameter[self.mv]
        self.liveData = self.motor_live_data[self.mv]

    def get_supported_motor_versions(self):
        return list(self.supported_motor_versions.keys())

    def get_rs232_settings(self, prop):
        return self.rs232[prop]

    def get_live_data_list(self):
        return self.liveData

    def get_parameter_group_list(self):
        return list(self.parameter.keys())

    def get_parameter_list(self, group_list):
        """ Returns a list of all parameters from a parameter group list
        """
        pars_list = []
        for group in group_list:
            for pars in self.parameter[group].values():
                par_dict = {}
                for par in pars:
                    if par == 'Address':
                        par_dict[par] = int(pars[par], 16)
                    if par == 'Value':
                        par_dict[par] = None
                    if par == 'decimal_place':
                        try:
                            int(pars[par])
                            par_dict[par] = pars[par]
                        except ValueError:
                            par_dict[par] = "0"
                    else:
                        par_dict[par] = pars[par]
                pars_list.append(par_dict)
        return pars_list

    def get_selected_motor_parameter(self):
        return self.selected_motor_parameter[self.mv]
